### Recuperar todo los trabajos
GET http://localhost:3000/jobs

### Recuperar todo los trabajos por id
GET http://localhost:3000/jobs/2

### Buscar
GET http://localhost:3000/jobs?title=Diseñador%20UX/UI
### Buscar location
GET http://localhost:3000/jobs?location=nueva%20york
### Buscar salario
GET http://localhost:3000/jobs?salary=60000.00

### Crear
POST http://localhost:3000/jobs
Content-Type: application/json

{
  "title": "Desarrollador Backend",
  "description": "Se busca desarrollador Backend con experiencia en Node.js y Express.",
  "location": "Tegucigalpa",
  "salary": 40000.00
}

### Actualizar
PATCH http://localhost:3000/jobs/5
Content-Type: application/json

{
    "title": "Desarrollador Blockchain"
}
